using Microsoft.AspNetCore.Mvc;
using MonitoringSystem.Data;
using MonitoringSystem.Helpers;
using MonitoringSystem.Models;
using System;
using System.Linq;

namespace MonitoringSystem.Controllers
{
    public class DriverDashboard : Controller
    {
        private readonly ApplicationDbContext _context;

        public DriverDashboard(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Driver()
        {
            var viewModel = new DriverDashboardViewModel
            {
                TripHistory = _context.Trips.OrderByDescending(t => t.TripID).ToList(),
                RegisteredStudents = _context.Students.Where(s => s.Status == "Active").ToList()
            };
            return View(viewModel);
        }

        // 1. INITIALIZE TRIP: Creates the record in SQL immediately
        [HttpPost]
        public IActionResult InitializeTrip([FromBody] Trip data)
        {
            try
            {
                if (data == null) return Json(new { success = false, message = "Mapping Failed" });

                data.Date = DateTime.Now.ToString("MM/dd/yyyy");
                data.StartTime = DateTime.Now.ToString("hh:mm tt");
                data.Status = "In Progress";
                data.TotalBoarded = 0;
                data.DriverName = AccountController.CurrentUser?.FullName ?? "Driver";

                if (AccountController.CurrentUser != null)
                    data.UserID = AccountController.CurrentUser.UserID;

                _context.Trips.Add(data);
                _context.SaveChanges();

                // Return the real numeric TripID generated by SQL Server
                return Json(new { success = true, dbTripID = data.TripID });
            }
            catch (Exception ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
        }

        // 2. RECORD SCAN: Links a Student to the specific Trip
        [HttpPost]
        public IActionResult RecordScan(string lrn, int tripId, bool isManual = false, string reason = "")
        {
            try
            {
                if (string.IsNullOrEmpty(lrn) || tripId <= 0)
                    return Json(new { success = false, message = "Invalid ID or Scan Data" });

                string cleanLrn = lrn.Trim();

                // DECRYPTION: If not manual, try to unlock the QR code
                if (!isManual)
                {
                    try
                    {
                        string input = lrn.Trim().Replace(" ", "+");
                        string decryptedData = SecurityHelper.Decrypt(input);

                        // Handle our formats: "STMS-VERIFIED|LS-2026-0101"
                        if (decryptedData.Contains("|"))
                            cleanLrn = decryptedData.Split("|")[1].Trim();
                    }
                    catch { /* If fails, treated as raw text */ }
                }

                // STEP 1: Find the Student
                // Search by StudentLRN OR by the QRCodeValue (LS-2026-XXXX)
                var student = _context.Students.FirstOrDefault(s => s.StudentLRN == cleanLrn)
                   ?? _context.Students.FirstOrDefault(s => _context.QRCodes.Any(q => q.QRCodeValue == cleanLrn && q.QRCodeID == s.QRCodeID));

                if (student == null)
                    return Json(new { success = false, message = "Student not found in registry." });

                if (student.Status == "Inactive")
                    return Json(new { success = false, message = "Access Denied: Student is Inactive." });

                // STEP 2: SAVE TRANSPORT ACTIVITY
                var newActivity = new TransportActivity
                {
                    StudentID = student.StudentID, // int FK
                    TripID = tripId,               // int FK
                    EntryMethod = isManual ? "Manual" : "QR",
                    Time = DateTime.Now.TimeOfDay,
                    ManualCheckInReason = isManual ? reason : "N/A"
                };

                _context.TransportActivities.Add(newActivity);

                if (isManual) student.ManualCheckInCount++;
                _context.SaveChanges();

                // STEP 3: GET REAL-TIME COUNT FROM SQL
                int realTimeCount = _context.TransportActivities.Count(a => a.TripID == tripId);

                return Json(new
                {
                    success = true,
                    currentCount = realTimeCount,
                    name = student.FullName,
                    photo = student.PhotoPath,
                    level = student.GradeLevel,
                    id = student.StudentSchoolID,
                    address = student.Address
                });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Database Error: " + ex.Message });
            }
        }

        // 3. SAVE TRIP: Finalizes the trip and updates the summary
        [HttpPost]
        public IActionResult SaveTrip([FromBody] Trip data)
        {
            if (data == null) return Json(new { success = false, message = "Mapping Error" });

            _context.ChangeTracker.Clear();
            var existingTrip = _context.Trips.FirstOrDefault(t => t.TripID == data.TripID);

            if (existingTrip != null)
            {
                // FORCE THE SERVER TO COUNT THE MANIFEST
                int finalCount = _context.TransportActivities.Count(a => a.TripID == data.TripID);

                existingTrip.TotalBoarded = finalCount;
                existingTrip.EndTime = DateTime.Now.ToString("hh:mm tt");
                existingTrip.Status = "Completed";

                _context.SaveChanges();

                return Json(new
                {
                    success = true,
                    message = $"Trip {existingTrip.TripID} finalized with {finalCount} students."
                });
            }
            return Json(new { success = false, message = "Trip not found." });
        }
    }
}